### ISSUE TITLE
Building fork of salmonIPM/develop

### ISSUE THREAD

**Issue by ebuhle** [mdscheuerell/AukeCoho#6]
Okay @DavidTallmon, here's what you'll need to do to build your forked copy of **salmonIPM**. In the R project for your version, do the following:

```r
pkgbuild::compile_dll()
roxygen2::roxygenize()
devtools::install(quick = FALSE, upgrade = FALSE)
```

More info [here](https://cran.r-project.org/web/packages/rstantools/vignettes/minimal-rstan-package.html), but that ought to do it. When you make a change and are ready to rebuild, you will probably find that you need to close and restart any R project that currently has your package loaded. I'm not sure why just detaching, and even removing the package isn't enough, but that's been my experience.

**Comment by DavidTallmon** [comment]
Done.

**Comment by DavidTallmon** [comment]
Sorry, I seem to have created another problem.
I moved the project to a different location on my computer today....with the idea that it would be more secure from my uni updates/backups.  I then tried to replicate the building of a forked copy and running the Ricker....just as I had w/ success yesterday.  Unfortunately, today I got this error message after calling the Ricker fit below:
> fit_Ricker <- salmonIPM(fishdata, stan_model = "IPM_SMaS_np", SR_fun = "Ricker",
+                         pars = c(stan_pars("IPM_SMaS_np"), "LL"),
+                         chains = 3, cores = 3, iter = 1500, warmup = 500,
+                         control = list(adapt_delta = 0.99, max_treedepth = 13))
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Variable "age_obs" does not exist.
 error in 'model292c19f36_IPM_SMaS_np' at line 347, column 9
  -------------------------------------------------
   345:   S_obs[which_S_obs] ~ lognormal(log(S[which_S_obs]), tau_S[pop[which_S_obs]]);  // observed spawners
   346:   target += sum(n_MSage_obs .* log(q_MS));  // obs wild age freq: n_MS
   347:   age_obs[i] ~ multinomial(q_MS[i])
                ^
   348:   target += sum(n_GRage_obs .* log(q_GR));  // obs wild age freq: n_age_obs[i] ~ multinomial(q_GR[i])
  -------------------------------------------------

Error in stanc(file = file, model_code = model_code, model_name = model_name,  : 
  failed to parse Stan model 'IPM_SMaS_np' due to the above error.

Just in case it's helpful, I attach the IPM_SMaS_np file (I had to add the .txt extension to get it to attach)
[IPM_SMaS_np.stan.txt](https://github.com/mdscheuerell/AukeCoho/files/4861267/IPM_SMaS_np.stan.txt)

and the history for the session........
[Rhistory.txt](https://github.com/mdscheuerell/AukeCoho/files/4861292/Rhistory.txt)

Any ideas, how I mucked this up?  I didn't do anything to the STAN code or the input file today...at least not consciously.

**Comment by mdscheuerell** [comment]
Hey @DavidTallmon. That msg suggests that perhaps some of the files were not moved over. Did you move everything inside the folder with the .Rproj file?

**Comment by ebuhle** [comment]
It looks like your copy of `IPM_SMaS_np.stan` has somehow gotten part of the comment from line 346 wrapped onto line 347, sans comment characters, where it is incorrectly being parsed as a statement. In the original file, line 346 reads

```stan
  target += sum(n_MSage_obs .* log(q_MS));  // obs wild age freq: n_MSage_obs[i] ~ multinomial(q_MS[i])
```

Is it possible that you accidentally entered a carriage return while you were editing the file? If not, then I can't account for it...unless...didn't you say that you opened this (or some other) file in WordPad during our Zoom call yesterday? Maybe that resulted in hard line breaks? If that's the case, then I'd recommend re-syncing everything from GitHub just to be on the safe side.

EDIT: I just saw that you said you didn't modify the .stan file since yesterday, when it was working. Clearly it got modified somehow, though, because this version shouldn't (and doesn't) parse.

**Comment by DavidTallmon** [comment]
I have no idea how that carriage return got in there.  I must've flinched
w/o realizing it when scanning through IPM_SMaS_np.stan and then saved it.
Apologies.
